---
openapi: "3.1.0"
info:
  contact:
    email: "devsupport@europace2.de"
    name: "Europace AG"
    url: "https://docs.api.europace.de"
  description:
    "As a loan provider get all the data of your applications for highly\
    \ effective validations and approvals."
  title: "Anträge API"
  version: "2.86"
servers:
  - url: "https://baufismart.api.europace.de"
security:
  - oauth_security: []
tags:
  - description: "All about mortage-applications and -approvals."
    name: "Antraege"
paths:
  /v2/antraege:
    get:
      description:
        "As loan provider, you'll get a list of all your applications,\
        \ sorted by lastChanged, paged and filterable."
      operationId: "getAll"
      security:
        - oauth_security:
            - "baufinanzierung:antrag:lesen"
        - oauth_security: []
      summary: "get list of all applications"
      tags:
        - "Antraege"
  /v2/antraege/{vorgang}:
    get:
      description: "As advisor, you'll get a list of all applications of your case."
      operationId: "getAntraegeByVorgangNummer"
      security:
        - oauth_security:
            - "baufinanzierung:antrag:lesen"
        - oauth_security: []
      summary: "get list of all applications of a case"
      tags:
        - "Antraege"
  /v2/antraege/{vorgang}/{antrag}:
    get:
      description:
        "As loan Provider, you'll get a list of approvals with data for\
        \ validation and decision."
      operationId: "getAntraege"
      security:
        - oauth_security:
            - "baufinanzierung:antrag:lesen"
        - oauth_security: []
      summary: "get list of approvals of an application"
      tags:
        - "Antraege"
  /v2/antraege/{vorgang}/{antrag}/{teilantrag}:
    get:
      description:
        "As loan Provider, you'll get all data of an application for validation\
        \ and decision."
      operationId: "getAntrag"
      security:
        - oauth_security:
            - "baufinanzierung:antrag:lesen"
        - oauth_security: []
      summary: "get application"
      tags:
        - "Antraege"
    patch:
      description:
        "As loan provider, update the planned approving date, the loan\
        \ officer contact details and your own reference for well informed advisors\
        \ and easy conversations with sales."
      operationId: "updateAntrag"
      security:
        - oauth_security:
            - "baufinanzierung:antrag:schreiben"
        - oauth_security: []
      summary: "patch application"
      tags:
        - "Antraege"
  /v2/antraege/{vorgang}/{antrag}/{teilantrag}/angebot:
    get:
      description:
        "As loan provider, you'll get all loan details wich are accepted\
        \ by the customer."
      operationId: "getAngebot"
      security:
        - oauth_security:
            - "baufinanzierung:antrag:lesen"
        - oauth_security: []
      summary: "get offer"
      tags:
        - "Antraege"
  /v2/antraege/{vorgang}/{antrag}/{teilantrag}/angebot/zahlungsplaene:
    get:
      description: "As loan provider, you'll get a redemption plan of the loan."
      operationId: "getZahlungsplaene"
      security:
        - oauth_security:
            - "baufinanzierung:antrag:lesen"
        - oauth_security: []
      summary: "get redemption plan"
      tags:
        - "Antraege"
  /v2/antraege/{vorgang}/{antrag}/{teilantrag}/ansprechpartner:
    get:
      description:
        "As loan provider, you'll get the contact details of the clerk\
        \ for communication."
      operationId: "getAnsprechpartner"
      security:
        - oauth_security:
            - "baufinanzierung:antrag:lesen"
        - oauth_security: []
      summary: "get clerk"
      tags:
        - "Antraege"
  /v2/antraege/{vorgang}/{antrag}/{teilantrag}/gegenangebot:
    post:
      description:
        "As loan provider, you can resend an adjusted offer, to create\
        \ a working solution for the customer. \n\nA counteroffer is an adjusted offer\
        \ based on the application set by the loan provider.\n\nIf a counteroffer\
        \ is created, the original offer will be marked as 'ABGELEHNT' and a new offer\
        \ will be created. The new offer is automatically marked as `UNTERSCHRIEBEN\
        \ ` from the loan provider. \n\nA single loan or a combination of loans can\
        \ be offered as a counteroffer."
      operationId: "erstelleGegenangebot"
      security:
        - oauth_security:
            - "baufinanzierung:antrag:schreiben"
            - "baufinanzierung:echtgeschaeft"
        - oauth_security: []
      summary: "create counteroffer"
      tags:
        - "Antraege"
  /v2/antraege/{vorgang}/{antrag}/{teilantrag}/nachricht:
    get:
      description:
        "As loan provider, you can send a message to the advisor to communicate\
        \ without a denied-state. \n\nImportant! Please prefer `set state` for communication\
        \ with advisor, because states are more helpful for process reporting. \n\n\
        This method should be your last choice."
      operationId: "addNachricht"
      security:
        - oauth_security:
            - "baufinanzierung:antrag:schreiben"
        - oauth_security: []
      summary: "send message"
      tags:
        - "Antraege"
    post:
      description:
        "As loan provider, you can send a message to the advisor to communicate\
        \ without a denied-state. \n\nImportant! Please prefer `set state` for communication\
        \ with advisor, because states are more helpful for process reporting. \n\n\
        This method should be your last choice."
      operationId: "addNachricht_1"
      security:
        - oauth_security:
            - "baufinanzierung:antrag:schreiben"
        - oauth_security: []
      summary: "send message"
      tags:
        - "Antraege"
  /v2/antraege/{vorgang}/{antrag}/{teilantrag}/status:
    get:
      description:
        "As loan provider, you can set a state for an application to inform\
        \ the advisor about your decision.\n\nIf you set a state for an application\
        \ the adivsor will be automatically informed by your descision and message.\
        \ You can use it, to send advisor a message if you choose the right state\
        \ and use the property `kommentar`."
      operationId: "setStatus"
      security:
        - oauth_security:
            - "baufinanzierung:antrag:schreiben"
        - oauth_security: []
      summary: "set state"
      tags:
        - "Antraege"
    post:
      description:
        "As loan provider, you can set a state for an application to inform\
        \ the advisor about your decision.\n\nIf you set a state for an application\
        \ the adivsor will be automatically informed by your descision and message.\
        \ You can use it, to send advisor a message if you choose the right state\
        \ and use the property `kommentar`."
      operationId: "setStatus_1"
      security:
        - oauth_security:
            - "baufinanzierung:antrag:schreiben"
        - oauth_security: []
      summary: "set state"
      tags:
        - "Antraege"
components:
  securitySchemes:
    oauth_security:
      bearerFormat: "JWT"
      in: "header"
      scheme: "bearer"
      type: "http"
