---
swagger: "2.0"
info:
  description: As a loan provider get all the data of your applications for highly effective validations and approvals.
  version: "2.57"
  title: Anträge API
  contact:
    name: Europace AG
    url: https://docs.api.europace.de
    email: devsupport@europace2.de
host: baufismart.api.europace.de
basePath: /
tags:
  - name: Antraege
    description: All about mortage-applications and -approvals.
schemes:
  - https
paths:
  /v2/antraege:
    get:
      tags:
        - Antraege
      summary: get all applications
      description: "As loan provider, you'll get a list of all your applications, sorted by lastChanged, paged and filterable."
      operationId: getAntraegeList
      security:
        - OAuth2:
            - baufinanzierung:antrag:lesen
  /v2/antraege/{vorgang}:
    get:
      tags:
        - Antraege
      summary: get applications of a case
      description: "As advisor, you'll get all applications of your case. "
      operationId: getAntraegeByVorgangNummer
      security:
        - OAuth2:
            - baufinanzierung:antrag:lesen
  /v2/antraege/{vorgang}/{antrag}:
    get:
      tags:
        - Antraege
      summary: get approvals of an application
      description: "As loan Provider, you'll get a list of approvals with data for validation and decision."
      operationId: getAntrag
      security:
        - OAuth2:
            - baufinanzierung:antrag:lesen
  /v2/antraege/{vorgang}/{antrag}/{teilantrag}:
    get:
      tags:
        - Antraege
      summary: get application
      description: "As loan Provider, you'll get all data of an application for validation and decision."
      operationId: getAntrag_1
      security:
        - OAuth2:
            - baufinanzierung:antrag:lesen
    patch:
      tags:
        - Antraege
      summary: patch application
      description: "As loan provider, update the planned approving date, the loan officer contact details and your own reference for well informed advisors and easy conversations with sales."
      operationId: updateAntrag
      security:
        - OAuth2:
            - baufinanzierung:antrag:schreiben
  /v2/antraege/{vorgang}/{antrag}/{teilantrag}/angebot:
    get:
      tags:
        - Antraege
      summary: get offer
      description: "As loan provider, you'll get all loan details wich are accepted by the customer."
      operationId: getAngebot
      security:
        - OAuth2:
            - baufinanzierung:antrag:lesen
  /v2/antraege/{vorgang}/{antrag}/{teilantrag}/angebot/zahlungsplaene:
    get:
      tags:
        - Antraege
      summary: get redemption plan
      description: "As loan provider, you'll get a redemption plan of the loan."
      operationId: getZahlungsplaene
      security:
        - OAuth2:
            - baufinanzierung:antrag:lesen
  /v2/antraege/{vorgang}/{antrag}/{teilantrag}/ansprechpartner:
    get:
      tags:
        - Antraege
      summary: get advisor
      description: "As loan provider, you'll get the contact details of the advisor for communication."
      operationId: getAnsprechpartner
      security:
        - OAuth2:
            - baufinanzierung:antrag:lesen
  /v2/antraege/{vorgang}/{antrag}/{teilantrag}/gegenangebot:
    post:
      tags:
        - Antraege
      summary: create counteroffer
      description: "As loan provider, you can resend an adjusted offer, to create a working solution for the customer. \n\nA counteroffer is an adjusted offer based on the application set by the loan provider.\n\nIf a counteroffer is created, the original offer will be marked as 'ABGELEHNT' and a new offer will be created. The new offer is automatically marked as `UNTERSCHRIEBEN ` from the loan provider. \n\nA single loan or a combination of loans can be offered as a counteroffer."
      operationId: erstelleGegenangebot
      security:
        - OAuth2:
            - baufinanzierung:antrag:schreiben
            - baufinanzierung:echtgeschaeft
  /v2/antraege/{vorgang}/{antrag}/{teilantrag}/nachricht:
    post:
      tags:
        - Antraege
      summary: send message
      description: "As loan provider, you can send a message to the advisor to communicate without a denied-state. \n\nImportant! Please prefer `set state` for communication with advisor, because states are more helpful for process reporting. \n\nThis method should be your last choice."
      operationId: addNachricht_1
      security:
        - OAuth2:
            - baufinanzierung:antrag:schreiben
  /v2/antraege/{vorgang}/{antrag}/{teilantrag}/status:
    post:
      tags:
        - Antraege
      summary: set state
      description: "As loan provider, you can set a state for an application to inform the advisor about your descision.\n\nIf you set a state for an application the adivsor will be automatically informed by your descision and message. You can use it, to send advisor a message if you choose the right state and use the property `kommentar`. "
      operationId: setAntragsStatus_1
      security:
        - OAuth2:
            - baufinanzierung:antrag:schreiben
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
  OAuth2:
    type: oauth2
    tokenUrl: https://api.europace.de/auth/access-token
    flow: application
    scopes:
      baufinanzierung:echtgeschaeft: to use api in production mode
      baufinanzierung:antrag:lesen: to get application information
      baufinanzierung:antrag:schreiben: "to update application data (eg state, loan office and own reference)"