---
swagger: "2.0"
info:
  description: Mit dieser API können die Anträge durch die Produktanbieter abgerufen werden. Dabei wird ausschließlich der Kontext des Produktanbieters eingenommen.
  version: "2.32"
  title: Anträge API
  contact:
    name: Europace AG
    url: www.europace2.de
    email: devsupport@europace2.de
host: baufismart.api.europace.de
basePath: /
tags:
  - name: Anträge
    description: Zugriff auf Anträge für die Kreditentscheidung
schemes:
  - https
paths:
  /v2/antraege:
    get:
      tags:
        - Anträge
      summary: Alle Anträge abrufen
      description: "Es werden alle Anträge ausgeliefert, die der authentifizierten Partner sehen darf. Offen: Sortierung, Pagination, Filterung"
      operationId: getAlleAntraege
      security:
        - OAuth2:
            - baufinanzierung:antrag:lesen
  /v2/antraege/{vorgang}:
    get:
      tags:
        - Anträge
      summary: Alle Anträge eines Vorgangs abrufen
      description: Als Parameter wird die Vorgangsnummer in der Form 'AB1234' verwendet.
      operationId: getAntraegeByVorgangNummer
      security:
        - OAuth2:
            - baufinanzierung:antrag:lesen
  /v2/antraege/{vorgang}/{antrag}:
    get:
      tags:
        - Anträge
      summary: Teilanträge eines Antrags abrufen
      description: Als Parameter wird die Vorgangs- und Antragsnummer in der Form 'AB1234/1' verwendet.
      operationId: getAntrag
      security:
        - OAuth2:
            - baufinanzierung:antrag:lesen
  /v2/antraege/{vorgang}/{antrag}/angebot:
    get:
      tags:
        - Anträge
      summary: Angebot des Antrags abrufen
      description: "Es handelt sich um das angenommene Angebot, das zu diesem Antrag geführt hat.  Nutze den Endpunkt /{vorgang}/{antrag}/{teilAntrag}/angebot"
      operationId: getAngebot_1
      security:
        - OAuth2:
            - baufinanzierung:antrag:lesen
      deprecated: true
  /v2/antraege/{vorgang}/{antrag}/{teilantrag}:
    get:
      tags:
        - Anträge
      summary: Einzelnen Antrag abrufen
      description: Als Parameter wird die komplette Antragsnummer in der Form 'AB1234/1/2' verwendet.
      operationId: getAntrag_1
      security:
        - OAuth2:
            - baufinanzierung:antrag:lesen
    patch:
      tags:
        - Anträge
      summary: Antrag aktualisieren
      description: Als Parameter wird die komplette Antragsnummer in der Form 'AB1234/1/2' verwendet. Es können mehrere Operationen gleichzeitig übertragen werden.
      operationId: updateAntrag
      security:
        - OAuth2:
            - baufinanzierung:antrag:schreiben
  /v2/antraege/{vorgang}/{antrag}/{teilantrag}/angebot:
    get:
      tags:
        - Anträge
      summary: Angebot des Antrags abrufen
      description: "Es handelt sich um das angenommene Angebot, das zu diesem Antrag geführt hat."
      operationId: getAngebot
      security:
        - OAuth2:
            - baufinanzierung:antrag:lesen
  /v2/antraege/{vorgang}/{antrag}/{teilantrag}/angebot/zahlungsplaene:
    get:
      tags:
        - Anträge
      summary: Die Zahlungsplaene (Tilgungs- & Sparpläne) des angenommenen Angebots.
      description: Als Parameter wird die komplette Antragsnummer in der Form 'AB1234/1/2' verwendet.
      operationId: getZahlungsplaene
      security:
        - OAuth2:
            - baufinanzierung:antrag:lesen
  /v2/antraege/{vorgang}/{antrag}/{teilantrag}/ansprechpartner:
    get:
      tags:
        - Anträge
      summary: Den Ansprechpartner (Vertrieb) des  Teilantrags abrufen.
      description: Als Parameter wird die komplette Antragsnummer in der Form 'AB1234/1/2' verwendet.
      operationId: getAnsprechpartner
      security:
        - OAuth2:
            - baufinanzierung:antrag:lesen
  /v2/antraege/{vorgang}/{antrag}/{teilantrag}/gegenangebot:
    post:
      tags:
        - Anträge
      summary: Ein Gegenangebot erstellen
      description: Als Parameter wird die komplette Antragsnummer in der Form 'AB1234/1/2' verwendet. Das übergebene Angebot wird sofort als Gegenangebot gestellt. Der alte Antrag wird abgelehnt.
      operationId: erstelleGegenangebot
      security:
        - OAuth2:
            - baufinanzierung:antrag:schreiben
            - baufinanzierung:echtgeschaeft
  /v2/antraege/{vorgang}/{antrag}/{teilantrag}/status:
    post:
      tags:
        - Anträge
      summary: Setzen des Antragsstatus
      operationId: setAntragsStatus_1
      security:
        - OAuth2:
            - baufinanzierung:antrag:schreiben
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
  OAuth2:
    type: oauth2
    tokenUrl: https://api.europace.de/auth/access-token
    flow: application
    scopes:
      baufinanzierung:echtgeschaeft: Für das Lesen und Bearbeiten von Anträgen im Echtgeschäft benötigt
      baufinanzierung:antrag:lesen: Auslesen von Anträgen
      baufinanzierung:antrag:schreiben: "Ändern von Daten eines Antrags (bspw. Antragsstatus, Kreditsachbearbeiter)"