name: Pull Request on Branch Push
on:
  push:
    branches:
      - "publish/*"
jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: pull-request
        uses: repo-sync/pull-request@v2
        with:
          source_branch: ""                                 # If blank, default: triggered branch
          destination_branch: "master"                      # If blank, default: master
          github_token: ${{ secrets.GITHUB_TOKEN }}
